# Generated by Django 5.0 on 2024-04-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kow_app", "0008_seller_products_last_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
